# Generated by Django 3.2.18 on 2023-02-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_table_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
