# Generated by Django 3.2.18 on 2023-03-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_delete_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
