# Generated by Django 3.2.18 on 2023-03-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_reservation_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='cost',
        ),
        migrations.AddField(
            model_name='table',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
