# Generated by Django 3.2.18 on 2023-03-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20230305_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='description',
            field=models.TextField(default='Book a table and  have taste of this exotic meal.'),
        ),
    ]
