# Generated by Django 3.2.18 on 2023-03-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20230307_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
