# Generated by Django 3.2.18 on 2023-03-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_table_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reseved_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='table',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
