# Generated by Django 3.2.18 on 2023-03-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20230308_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
