# Generated by Django 3.2.18 on 2023-03-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_tableimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
