# Generated by Django 3.2.18 on 2023-03-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reseved_on',
            new_name='reserved_on',
        ),
    ]
