# Generated by Django 3.2.18 on 2023-03-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_auto_20230319_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('snacks', 'Snacks'), ('main', 'Main'), ('dessert', 'Dessert')], default='snacks', max_length=7),
        ),
    ]
