# Generated by Django 3.2.18 on 2023-03-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_alter_food_food_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableImage',
        ),
    ]
