# Generated by Django 3.2.18 on 2023-03-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_delete_tableimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
