# Generated by Django 3.2.18 on 2023-05-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='table',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
